tap "homebrew/core"
tap "homebrew/bundle"
brew "awscli"
brew "bash"
brew "bash-completion@2"
brew "coreutils"
brew "git"
brew "jo"
brew "jq"
brew "kotlin"
brew "maven"
brew "maven-completion"
brew "node@8", link: true
brew "peco"
brew "ruby-completion"
brew "ruby@2.3", link: true
