colorscheme desert
set autoindent
set clipboard=unnamed
set expandtab
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set list
set listchars=eol:<,tab:>-,trail:-,extends:>,precedes:<
set mouse=a
set number
set ruler
set scrolloff=3
set shiftround
set shiftwidth=4
set showmode
set tabstop=4
set whichwrap=b,s,h,l,<,>,[,],~
syntax on
