set autoindent
set belloff=backspace,cursor,error,esc
set clipboard=unnamed
set expandtab
set hlsearch
set ignorecase
set incsearch
set laststatus=2
set list
set listchars=tab:>-,trail:-,extends:>,precedes:<
set noswapfile
set number
set scrolloff=5
set shiftround
set shiftwidth=4
set smartcase
set tabstop=4
set whichwrap=b,s,h,l,<,>,[,]
syntax on
